### PR TITLE
Adds support for conditional anonymisation of columns.

### PR DESCRIPTION
**Pull request by usoban**
All relevant changes are in `anonymiser.go` file. 

Ignore other stuff, it's just package rename which still needs to be fixed.

### CODE REVIEW

**Comment by usoban** [comment]
Tried to revert changes of `github.com/usoban/klepto`  back to `github.com/hellofresh/klepto` but still does not recompile (even though I've moved the sources to `$GOROOT/src/github.com/hellofresh/klepto`. Need to solve that next.

**Comment by lalabuy948** [comment]
So, the problem with `deps` I guess, not with renaming, when I installed `github.com/antonmedv/expr` that package via `deps`, Compile function was mission. If you would do `go get github.com/antonmedv/expr` and remove that package from `vendor` it works fine. 
And I compiled project on your branch

**Comment by usoban** [comment]
Yeah I actually did install `github.com/antonmedv/expr` via `go get github.com/antonmedv/expr` :)

The current branch compiles just fine and works. Still, there's currently two problems with this branch:

-  I'd like to rename all packages back to `github.com/hellofresh/klepto` (remember we've been debugging why recompilation does not pick up any changes, and we renamed all packages to `github.com/usoban/klepto`, because I've f*cked up and actually created a new package locally :see_no_evil: ). 
If I revert all the renames, and check out this branch into `$GOROOT/src/github.com/hellofresh/klepto` (into the "correct" package path), the situation repeats - no changes from this branch are picked up during recompilation

-  The second problem is actually just performance optimization inside `anonymiser.go` file. The evaluation rules are compiled every time we want to evaluate the rule (https://github.com/usoban/klepto/pull/1/files#diff-193869b0771795a3496d4ec90d2e096aR93). We could, however, compile these upfront when reading the configuration.

**Comment by lalabuy948** [comment]
I kinda don't understand why you would like to rename package back to `github.com/hellofresh/klepto`, coz you did the fork and it make sense to rename it to `github.com/usoban/klepto` and work as your local package with all necessary changes.  

About the perfomance, we can pass an argument or store that rule somewhere in the config, not to recompile it each time.

**Comment by usoban** [comment]
OK, maybe you're right that package should be renamed. I'm not that familiar with Golang ecosystem, but usually in other ecosystems forking does not require exactly package renaming :)

I've just pushed changes which add rule compilation and there is a significant performance improvement :)

**Comment by usoban** [comment]
One other thing which could be improved ... I used a "magic string" as a return value from a rule, which indicates that anonymisation should be skipped. The constant is defined here https://github.com/usoban/klepto/pull/1/files#diff-193869b0771795a3496d4ec90d2e096aR23

Any better idea than using a magic string?

**Comment by lalabuy948** [comment]
I dont see big problem using 'magic string', but i will think about how to wrap it more nicely.

**Comment by usoban** [comment]
OK fixed and added the following things:

- reverted package rename back to `github.com/hellofresh/klepto`
- added better support for skipping anonymisation via Option implementation
- added a section for conditional anonymisation to README
- formatted new/modified files with go fmt
- added better support for handling `nil` column values (`Value/2` converts it to empty string, added `IsNil/2` function for checking of `nil`)

**Review by lalabuy948 — APPROVED** [review]
Beautiful

**Pull request merged**
